PROJECT_ROOT = $(shell pwd)

STM32G071:
	make -C HAL/STM32G071/ PROJECT_ROOT=$(PROJECT_ROOT) -j $(nproc)

STM32F303:
	make -C HAL/STM32F303/ PROJECT_ROOT=$(PROJECT_ROOT) -j $(nproc)

PATTERN_TEST:
	make -C python_test PROJECT_ROOT=$(PROJECT_ROOT) -j $(nproc)

all: STM32G071 STM32F303

clean:
	make -C HAL/STM32G071/ PROJECT_ROOT=$(PROJECT_ROOT) clean
	make -C HAL/STM32G071/ PROJECT_ROOT=$(PROJECT_ROOT) clean
