version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: install dependencies
          command: "apt-get update \
 apt-get install make"

      - run:
          name: build all
          command: make all

      - run:
          name: build test
          command: make test
