version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: update apt
          command: apt-get update

      - run: 
          name: install tools
          command: apt-get -y install build-essential gcc-arm-none-eabi

      - run:
          name: build all
          command: make all

      - run:
          name: build test
          command: make test

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
